### ISSUE TITLE
'module' object has no attribute 'decode_rs

### ISSUE THREAD

**Issue by dl7oap** [esa/gr-opssat#7]
most of the installation is done. but now i'm stuck at this point.

```
Executing: /usr/bin/python -u /home/andreas/Dokumente/Development/dl7oap/gr-opssat/apps/os_demod_decode.py

Traceback (most recent call last):
  File "/home/andreas/Dokumente/Development/dl7oap/gr-opssat/apps/os_demod_decode.py", line 282, in <module>
    main()
  File "/home/andreas/Dokumente/Development/dl7oap/gr-opssat/apps/os_demod_decode.py", line 270, in main
    tb = top_block_cls()
  File "/home/andreas/Dokumente/Development/dl7oap/gr-opssat/apps/os_demod_decode.py", line 91, in __init__
    self.satellites_decode_rs_0 = satellites.decode_rs(True, 0)
AttributeError: 'module' object has no attribute 'decode_rs'
```

i tried to compile the hierarchical flowgraph ./compile_hierarchical.sh when installing the newest gr-satellites master branch, but this, too, fails:
Block key "digital_correlate_access_code_tag_xx" not found
Validation failed:

```
Block - pad_source_0 - Pad Source(pad_source):
	Source - out(0):
		Port is not connected.

Block - satellites_fixedlen_tagger_0_0_0 - Fixed Length Packet Tagger(satellites_fixedlen_tagger):
	Sink - in(0):
		Port is not connected.
Error during file compilation.
Block key "digital_correlate_access_code_tag_xx" not found
Validation failed:

Block - pad_source_0 - Pad Source(pad_source):
	Source - out(0):
		Port is not connected.

Block - satellites_fixedlen_tagger_0_0_0 - Fixed Length Packet Tagger(satellites_fixedlen_tagger):
	Sink - in(0):
		Port is not connected.
Error during file compilation.
```
so i think, i will give up here with decoding via gnu-radio  and i just will record wav files from the telemetry.

- gpredict, gqrx, os_uhf_rx.grc and "OPS-SAT UHF Desktop" is running without problems. but os_demod_decode.grc is hard to get running.

**Comment by dl7oap** [comment]
is working now. think it was swig which was missing.
