### ISSUE TITLE
gr-satellites dependency version

### ISSUE THREAD

**Issue by DL7AD** [esa/gr-opssat#9]
Hi,

I'm trying to get os_demod_decode.grc working on my computer. However it seems that the satellite package has some data type problem. Which version of gr-satellites is required? I'm running v1.8.2 at the moment because later versions require Gnuradio 3.8.

```<<< Welcome to GNU Radio Companion 3.7.11 >>>

Block paths:
	/home/sven/.grc_gnuradio
	/usr/share/gnuradio/grc/blocks
	/usr/local/share/gnuradio/grc/blocks

Loading: "/src/gr-opssat/apps/os_uhf_rx.grc"
>>> Done

Loading: "/src/gr-opssat/apps/os_demod_decode.grc"
>>> Done

Generating: '/src/gr-opssat/apps/os_demod_decode.py'
>>> Warning: This flow graph may not have flow control: no audio or RF hardware blocks found. Add a Misc->Throttle block to your flow graph to avoid CPU congestion.

Executing: /usr/bin/python -u /src/gr-opssat/apps/os_demod_decode.py

Traceback (most recent call last):
  File "/src/gr-opssat/apps/os_demod_decode.py", line 37, in <module>
    import satellites
  File "/usr/local/lib/python2.7/dist-packages/satellites/__init__.py", line 103, in <module>
    from sat_3cat_1_telemetry_parser import sat_3cat_1_telemetry_parser
  File "/usr/local/lib/python2.7/dist-packages/satellites/sat_3cat_1_telemetry_parser.py", line 26, in <module>
    import sat_3cat_1_telemetry
  File "/usr/local/lib/python2.7/dist-packages/satellites/sat_3cat_1_telemetry.py", line 109, in <module>
    'beacon_id' / BeaconID * set_delta_min_delay,\
TypeError: unsupported operand type(s) for *: 'Renamed' and 'function'

>>> Done```

**Comment by mathzol** [comment]
I think its python-construct, you use a wrong version. 2.9.x needed.

**Comment by DL7AD** [comment]
Thanks for the reply. Yes I found that already and pip didn't want to upgrade it, so I upgraded it from source, which worked but as I started GNURadio, construct downgraded somehow.

Anyway there's something going wrong fundamentally with my Python installation atm. So not a bug.

**Comment by mathzol** [comment]
You have to remove the apt version first then install from pip 2.9.x. For the operating system the apt version is higher "priority".

**Comment by DL7AD** [comment]
@mathzol Still have that issue.

1. Check Construct isn't installed via apt
2. construct is not available
3. PIP reports it's installed
4. Uninstall and reinstall is again with PIP
5. Check availability and version => OK
6. Run gnuradio => construct is gone again

```
sven@sven-notebook:/src/gr-opssat$ aptitude search construct
p   boa-constructor                                                                        - RAD tool for Python and wxWindows application                                                    
p   libmoosex-blessed-reconstruct-perl                                                     - Data::Visitor for creating Moose objects                                                         
p   libmoosex-strictconstructor-perl                                                       - Make your object constructors blow up on unknown attributes                                      
p   libmoox-strictconstructor-perl                                                         - make Moo-based object constructors blow up on unknown attributes                                 
p   libmousex-strictconstructor-perl                                                       - Mouse extension for making object constructors die on unknown attributes                         
p   mime-construct                                                                         - construct/send MIME messages from the command line                                               
p   node-babel-plugin-syntax-class-constructor-call                                        - Allow parsing of class constructor calls                                                         
p   node-babel-plugin-transform-class-constructor-call                                     - Enable new.target in ES2015 classes                                                              
p   python-construct                                                                       - powerful declarative parser (and builder) for binary data                                        
p   python-construct.legacy                                                                - legacy fork of declarative binary data parser/builder (Python 2)                                 
v   python2.7-construct                                                                    -                                                                                                  
p   python3-construct                                                                      - powerful declarative parser (and builder) for binary data                                        
p   python3-construct.legacy                                                               - legacy fork of declarative binary data parser/builder (Python 3)                                 
p   ruby-test-construct                                                                    - Ruby library that creates temporary files and directories for testing                            
sven@sven-notebook:/src/gr-opssat$ pip install^C
sven@sven-notebook:/src/gr-opssat$ python
Python 2.7.17 (default, Nov  7 2019, 10:07:09) 
[GCC 7.4.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import construct
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named construct
>>> 
sven@sven-notebook:/src/gr-opssat$ sudo pip install construct
DEPRECATION: A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
WARNING: The directory '/home/sven/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
WARNING: The directory '/home/sven/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already satisfied: construct in /usr/local/lib/pypy2.7/dist-packages (2.9.45)
sven@sven-notebook:/src/gr-opssat$ sudo pip uninstall construct
DEPRECATION: A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
WARNING: The directory '/home/sven/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Uninstalling construct-2.9.45:
  Would remove:
    /usr/local/lib/pypy2.7/dist-packages/construct-2.9.45.dist-info/*
    /usr/local/lib/pypy2.7/dist-packages/construct/*
Proceed (y/n)? y
  Successfully uninstalled construct-2.9.45
sven@sven-notebook:/src/gr-opssat$ sudo pip install construct
DEPRECATION: A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
WARNING: The directory '/home/sven/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
WARNING: The directory '/home/sven/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Processing /home/sven/.cache/pip/wheels/22/73/01/9e7468947349b14ce8f07c3fc7b430b3a4ddad0837cda6ea73/construct-2.9.45-pp2510-none-any.whl
Installing collected packages: construct
Successfully installed construct-2.9.45
sven@sven-notebook:/src/gr-opssat$ python
Python 2.7.17 (default, Nov  7 2019, 10:07:09) 
[GCC 7.4.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import construct
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named construct
>>> 
sven@sven-notebook:/src/gr-opssat$ cd ../construct/
sven@sven-notebook:/src/construct$ make installdeps 
apt-get install python3.6 python2.7 pypy python3-sphinx --upgrade
E: Could not open lock file /var/lib/dpkg/lock-frontend - open (13: Permission denied)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), are you root?
Makefile:32: recipe for target 'installdeps' failed
make: *** [installdeps] Error 100
sven@sven-notebook:/src/construct$ sudo make installdeps 
apt-get install python3.6 python2.7 pypy python3-sphinx --upgrade
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python3-sphinx is already the newest version (1.6.7-1ubuntu1).
pypy is already the newest version (5.10.0+dfsg-3build2).
python2.7 is already the newest version (2.7.17-1~18.04).
python3.6 is already the newest version (3.6.9-1~18.04).
The following packages were automatically installed and are no longer required:
  kwayland-data kwayland-integration libdbusmenu-qt5-2 libfam0 libgflags2.2 libgnutls-openssl27 libgoogle-glog0v5 libhfstospell9 libisl15 libkf5archive5 libkf5attica5 libkf5auth-data
  libkf5auth5 libkf5codecs-data libkf5codecs5 libkf5completion-data libkf5completion5 libkf5config-bin libkf5config-data libkf5configcore5 libkf5configgui5 libkf5configwidgets-data
  libkf5configwidgets5 libkf5coreaddons-data libkf5coreaddons5 libkf5crash5 libkf5dbusaddons-bin libkf5dbusaddons-data libkf5dbusaddons5 libkf5globalaccel-bin libkf5globalaccel-data
  libkf5globalaccel5 libkf5globalaccelprivate5 libkf5guiaddons5 libkf5i18n-data libkf5i18n5 libkf5iconthemes-bin libkf5iconthemes-data libkf5iconthemes5 libkf5idletime5
  libkf5itemviews-data libkf5itemviews5 libkf5notifications-data libkf5notifications5 libkf5service-bin libkf5service-data libkf5service5 libkf5sonnet5-data libkf5sonnetcore5
  libkf5sonnetui5 libkf5textwidgets-data libkf5textwidgets5 libkf5waylandclient5 libkf5widgetsaddons-data libkf5widgetsaddons5 libkf5windowsystem-data libkf5windowsystem5 libkf5xmlgui-bin
  libkf5xmlgui-data libkf5xmlgui5 liblimesuite17.12-1 libllvm6.0:i386 libllvm7 libllvm7:i386 libnewlib-arm-none-eabi libnewlib-dev libphonon4qt5-4 libpolkit-qt5-1-1 libqt5script5
  libqt5texttospeech5 libstdc++-arm-none-eabi-newlib libtecla1 libusb-0.1-4 libvoikko1 limesuite-udev phonon4qt5 phonon4qt5-backend-vlc soapyosmo-common0.6 soapysdr0.6-module-lms7
  soapysdr0.6-module-osmosdr sonnet-plugins
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
python3.6 -m pip install pytest pytest-benchmark pytest-cov enum34 numpy arrow ruamel.yaml --upgrade
The directory '/home/sven/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/sven/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already up-to-date: pytest in /usr/local/lib/python3.6/dist-packages
Requirement already up-to-date: pytest-benchmark in /usr/local/lib/python3.6/dist-packages
Requirement already up-to-date: pytest-cov in /usr/local/lib/python3.6/dist-packages
Requirement already up-to-date: enum34 in /usr/local/lib/python3.6/dist-packages
Requirement already up-to-date: numpy in /usr/local/lib/python3.6/dist-packages
Requirement already up-to-date: arrow in /usr/local/lib/python3.6/dist-packages
Requirement already up-to-date: ruamel.yaml in /home/sven/.local/lib/python3.6/site-packages
Requirement already up-to-date: pluggy<1.0,>=0.12 in /usr/local/lib/python3.6/dist-packages (from pytest)
Requirement already up-to-date: wcwidth in /usr/local/lib/python3.6/dist-packages (from pytest)
Requirement already up-to-date: py>=1.5.0 in /usr/local/lib/python3.6/dist-packages (from pytest)
Requirement already up-to-date: packaging in /usr/local/lib/python3.6/dist-packages (from pytest)
Requirement already up-to-date: more-itertools>=4.0.0 in /usr/local/lib/python3.6/dist-packages (from pytest)
Requirement already up-to-date: importlib-metadata>=0.12; python_version < "3.8" in /usr/local/lib/python3.6/dist-packages (from pytest)
Requirement already up-to-date: attrs>=17.4.0 in /usr/local/lib/python3.6/dist-packages (from pytest)
Requirement already up-to-date: py-cpuinfo in /usr/local/lib/python3.6/dist-packages (from pytest-benchmark)
Requirement already up-to-date: coverage>=4.4 in /usr/local/lib/python3.6/dist-packages (from pytest-cov)
Requirement already up-to-date: python-dateutil in /usr/local/lib/python3.6/dist-packages (from arrow)
Requirement already up-to-date: ruamel.yaml.clib>=0.1.2; platform_python_implementation == "CPython" and python_version < "3.8" in /usr/local/lib/python3.6/dist-packages (from ruamel.yaml)
Requirement already up-to-date: six in /usr/local/lib/python3.6/dist-packages (from packaging->pytest)
Requirement already up-to-date: pyparsing>=2.0.2 in /usr/local/lib/python3.6/dist-packages (from packaging->pytest)
Requirement already up-to-date: zipp>=0.5 in /usr/local/lib/python3.6/dist-packages (from importlib-metadata>=0.12; python_version < "3.8"->pytest)
python2.7 -m pip install pytest pytest-benchmark pytest-cov enum34 numpy arrow ruamel.yaml --upgrade
The directory '/home/sven/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/sven/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already up-to-date: pytest in /usr/local/lib/python2.7/dist-packages
Requirement already up-to-date: pytest-benchmark in /usr/local/lib/python2.7/dist-packages
Requirement already up-to-date: pytest-cov in /usr/local/lib/python2.7/dist-packages
Requirement already up-to-date: enum34 in /usr/lib/python2.7/dist-packages
Requirement already up-to-date: numpy in /usr/local/lib/python2.7/dist-packages
Requirement already up-to-date: arrow in /usr/local/lib/python2.7/dist-packages
Requirement already up-to-date: ruamel.yaml in /usr/local/lib/python2.7/dist-packages
Requirement already up-to-date: importlib-metadata>=0.12; python_version < "3.8" in /usr/local/lib/python2.7/dist-packages (from pytest)
Requirement already up-to-date: funcsigs>=1.0; python_version < "3.0" in /usr/lib/python2.7/dist-packages (from pytest)
Requirement already up-to-date: py>=1.5.0 in /usr/local/lib/python2.7/dist-packages (from pytest)
Requirement already up-to-date: pathlib2>=2.2.0; python_version < "3.6" in /usr/local/lib/python2.7/dist-packages (from pytest)
Requirement already up-to-date: six>=1.10.0 in /usr/local/lib/python2.7/dist-packages (from pytest)
Requirement already up-to-date: pluggy<1.0,>=0.12 in /usr/local/lib/python2.7/dist-packages (from pytest)
Requirement already up-to-date: attrs>=17.4.0 in /usr/local/lib/python2.7/dist-packages (from pytest)
Requirement already up-to-date: more-itertools<6.0.0,>=4.0.0; python_version <= "2.7" in /usr/local/lib/python2.7/dist-packages (from pytest)
Requirement already up-to-date: atomicwrites>=1.0 in /usr/local/lib/python2.7/dist-packages (from pytest)
Requirement already up-to-date: packaging in /usr/local/lib/python2.7/dist-packages (from pytest)
Requirement already up-to-date: wcwidth in /usr/local/lib/python2.7/dist-packages (from pytest)
Requirement already up-to-date: py-cpuinfo in /usr/local/lib/python2.7/dist-packages (from pytest-benchmark)
Requirement already up-to-date: statistics; python_version < "3.4" in /usr/local/lib/python2.7/dist-packages (from pytest-benchmark)
Requirement already up-to-date: coverage>=4.4 in /usr/local/lib/python2.7/dist-packages (from pytest-cov)
Requirement already up-to-date: backports.functools-lru-cache>=1.2.1; python_version == "2.7" in /usr/local/lib/python2.7/dist-packages (from arrow)
Requirement already up-to-date: python-dateutil in /usr/local/lib/python2.7/dist-packages (from arrow)
Requirement already up-to-date: ruamel.yaml.clib>=0.1.2; platform_python_implementation == "CPython" and python_version < "3.8" in /usr/local/lib/python2.7/dist-packages (from ruamel.yaml)
Requirement already up-to-date: ruamel.ordereddict; platform_python_implementation == "CPython" and python_version <= "2.7" in /usr/local/lib/python2.7/dist-packages (from ruamel.yaml)
Requirement already up-to-date: zipp>=0.5 in /usr/local/lib/python2.7/dist-packages (from importlib-metadata>=0.12; python_version < "3.8"->pytest)
Requirement already up-to-date: configparser>=3.5; python_version < "3" in /usr/local/lib/python2.7/dist-packages (from importlib-metadata>=0.12; python_version < "3.8"->pytest)
Requirement already up-to-date: contextlib2; python_version < "3" in /usr/local/lib/python2.7/dist-packages (from importlib-metadata>=0.12; python_version < "3.8"->pytest)
Requirement already up-to-date: scandir; python_version < "3.5" in /usr/local/lib/python2.7/dist-packages (from pathlib2>=2.2.0; python_version < "3.6"->pytest)
Requirement already up-to-date: pyparsing>=2.0.2 in /usr/local/lib/python2.7/dist-packages (from packaging->pytest)
Requirement already up-to-date: docutils>=0.3 in /usr/local/lib/python2.7/dist-packages (from statistics; python_version < "3.4"->pytest-benchmark)
pypy      -m pip install pytest pytest-benchmark pytest-cov enum34       arrow             --upgrade
DEPRECATION: A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
WARNING: The directory '/home/sven/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
WARNING: The directory '/home/sven/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already up-to-date: pytest in /usr/local/lib/pypy2.7/dist-packages (4.6.8)
Requirement already up-to-date: pytest-benchmark in /usr/local/lib/pypy2.7/dist-packages (3.2.2)
Requirement already up-to-date: pytest-cov in /usr/local/lib/pypy2.7/dist-packages (2.8.1)
Requirement already up-to-date: enum34 in /usr/local/lib/pypy2.7/dist-packages (1.1.6)
Requirement already up-to-date: arrow in /usr/local/lib/pypy2.7/dist-packages (0.15.4)
Requirement already satisfied, skipping upgrade: py>=1.5.0 in /usr/local/lib/pypy2.7/dist-packages (from pytest) (1.8.0)
Requirement already satisfied, skipping upgrade: six>=1.10.0 in /usr/local/lib/pypy2.7/dist-packages (from pytest) (1.13.0)
Requirement already satisfied, skipping upgrade: packaging in /usr/local/lib/pypy2.7/dist-packages (from pytest) (19.2)
Requirement already satisfied, skipping upgrade: attrs>=17.4.0 in /usr/local/lib/pypy2.7/dist-packages (from pytest) (19.3.0)
Requirement already satisfied, skipping upgrade: atomicwrites>=1.0 in /usr/local/lib/pypy2.7/dist-packages (from pytest) (1.3.0)
Requirement already satisfied, skipping upgrade: pluggy<1.0,>=0.12 in /usr/local/lib/pypy2.7/dist-packages (from pytest) (0.13.1)
Requirement already satisfied, skipping upgrade: wcwidth in /usr/local/lib/pypy2.7/dist-packages (from pytest) (0.1.7)
Requirement already satisfied, skipping upgrade: funcsigs>=1.0; python_version < "3.0" in /usr/local/lib/pypy2.7/dist-packages (from pytest) (1.0.2)
Requirement already satisfied, skipping upgrade: pathlib2>=2.2.0; python_version < "3.6" in /usr/local/lib/pypy2.7/dist-packages (from pytest) (2.3.5)
Requirement already satisfied, skipping upgrade: importlib-metadata>=0.12; python_version < "3.8" in /usr/local/lib/pypy2.7/dist-packages (from pytest) (1.3.0)
Requirement already satisfied, skipping upgrade: more-itertools<6.0.0,>=4.0.0; python_version <= "2.7" in /usr/local/lib/pypy2.7/dist-packages (from pytest) (5.0.0)
Requirement already satisfied, skipping upgrade: py-cpuinfo in /usr/local/lib/pypy2.7/dist-packages (from pytest-benchmark) (5.0.0)
Requirement already satisfied, skipping upgrade: statistics; python_version < "3.4" in /usr/local/lib/pypy2.7/dist-packages (from pytest-benchmark) (1.0.3.5)
Requirement already satisfied, skipping upgrade: coverage>=4.4 in /usr/local/lib/pypy2.7/dist-packages (from pytest-cov) (5.0)
Requirement already satisfied, skipping upgrade: python-dateutil in /usr/local/lib/pypy2.7/dist-packages (from arrow) (2.8.1)
Requirement already satisfied, skipping upgrade: backports.functools-lru-cache>=1.2.1; python_version == "2.7" in /usr/local/lib/pypy2.7/dist-packages (from arrow) (1.6.1)
Requirement already satisfied, skipping upgrade: pyparsing>=2.0.2 in /usr/local/lib/pypy2.7/dist-packages (from packaging->pytest) (2.4.5)
Requirement already satisfied, skipping upgrade: scandir; python_version < "3.5" in /usr/local/lib/pypy2.7/dist-packages (from pathlib2>=2.2.0; python_version < "3.6"->pytest) (1.10.0)
Requirement already satisfied, skipping upgrade: zipp>=0.5 in /usr/local/lib/pypy2.7/dist-packages (from importlib-metadata>=0.12; python_version < "3.8"->pytest) (0.6.0)
Requirement already satisfied, skipping upgrade: contextlib2; python_version < "3" in /usr/local/lib/pypy2.7/dist-packages (from importlib-metadata>=0.12; python_version < "3.8"->pytest) (0.6.0.post1)
Requirement already satisfied, skipping upgrade: configparser>=3.5; python_version < "3" in /usr/local/lib/pypy2.7/dist-packages (from importlib-metadata>=0.12; python_version < "3.8"->pytest) (4.0.2)
Requirement already satisfied, skipping upgrade: docutils>=0.3 in /usr/local/lib/pypy2.7/dist-packages (from statistics; python_version < "3.4"->pytest-benchmark) (0.15.2)
sven@sven-notebook:/src/construct$ python
Python 2.7.17 (default, Nov  7 2019, 10:07:09) 
[GCC 7.4.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import construct
>>> print
KeyboardInterrupt
>>> construct.version
(2, 9, 46)
>>> 
sven@sven-notebook:/src/construct$ cd ../gr-opssat/apps/
sven@sven-notebook:/src/gr-opssat/apps$ python os_demod_decode.py 
Traceback (most recent call last):
  File "os_demod_decode.py", line 37, in <module>
    import satellites
  File "/usr/local/lib/python2.7/dist-packages/satellites/__init__.py", line 56, in <module>
    from funcube_telemetry_parser import funcube_telemetry_parser
  File "/usr/local/lib/python2.7/dist-packages/satellites/funcube_telemetry_parser.py", line 25, in <module>
    import funcube_telemetry
  File "/usr/local/lib/python2.7/dist-packages/satellites/funcube_telemetry.py", line 21, in <module>
    from construct import *
ImportError: No module named construct
```

**Comment by mathzol** [comment]
How did you install pip? I think you need to use the APT version, because your pip packages path is /usr/local/lib/pypy2.7/ instead of /usr/local/lib/python2.7/ . Or what is in your PYTHONPATH envirotment variable? You could add your pip packages path to like this: export PYTHONPATH=$PYTHONPATH:/usr/local/lib/pypy2.7/
In current terminal session it will work, if it works you have to apply this PYTHONPATH to your whole system.

**Comment by DL7AD** [comment]
PIP was install via APT. I didn't see that construct was installed elsewhere. PYTHONPATH was empty (scratching my head) and even setting it, didn't do anything.
Since I will reinstall the PC anyway, I moved the library now (though it's not the nicest way to do it). It works now.

Thanks for your help. I'm looking forward receiving OPS-SAT tomorrow by 0440Z.

**Comment by mathzol** [comment]
73 and have a good receive ;)
